# docker-compose.yml
version: "3"
services:
  db:
    image: mongo
    ports:
      - "27017:27017"
  book-api:
    env_file: .env
    volumes:
      - .:/home/app/
      - /home/app/node_modules
    build: .
    depends_on:
      - db
    ports:
      - "3000:3000"
      - "9229:9229"
    command: npm run watch